### ISSUE TITLE
Result contracts

### ISSUE THREAD

**Issue by jackfirth** [jackfirth/rebellion#229]
There should be contract combinators for [results][results]. Signatures:

```racket
(result/c [success-contract chaperone-contract?]
          [failure-contract chaperone-contract?]) -> chaperone-contract?

(success/c [contract chaperone-contract?]) -> chaperone-contract?

(failure/c [contract chaperone-contract?]) -> chaperone-contract?
```

A `(result/c a b)` contract should be equivalent to `(or/c (success/c a) (failure/c b))`.

[results]: https://docs.racket-lang.org/rebellion/Results.html

**Comment by rocketnia** [comment]
Although it doesn't seem like it at first, I think these arguments tend to be more readable the other way around. The success type is often more complex than the failure type, so putting the failure type first tends to shorten the visual distance separating the operator from its arguments.

For instance, putting the failure type first can come in handy when nesting multiple layers of `(result/c ... (result/c ... ...))` or `(-> ... (result/c ... (-> ... (result/c ... ...))))`.

Anyway, no worries either way.

**Comment by jackfirth** [comment]
I think the failure type should almost always be a simple predicate, because you should define a data type to encapsulate your possible failures. So instead of `(result/c ... (something complicated))` you ought to define a wrapper type like `(define-wrapper-type my-failure-case)` and use `(result/c ... my-failure-case?)`. That's the approach I'll be taking in the [chess package][chess-package] I wrote, specifically for the [chess patches][chess-patches] API.

[chess-package]: https://github.com/jackfirth/chess/
[chess-patches]: https://docs.racket-lang.org/chess/Chess_Patches.html

**Comment by jackfirth** [comment]
Oops, I misread your comment. Now I see what you mean.

In general, I think that sort of nesting should be _discouraged_ rather than encouraged. If a contract is that complex, its components should be extracted out either by making helper contract combinators or defining new data types. Plus, I really don't want the result type to do things in the exact opposite order of Rust's result type.

**Comment by rocketnia** [comment]
> I think the failure type should almost always be a simple predicate

That's a little stronger claim than I was making, but I agree. :) The failure contract is usually a simple predicate like `my-failure-case?`. It's hard for the success contract to get any simpler than that, so between the two, the success contract tends to be the more verbose one.

> In general, I think complex nesting like that should be *discouraged* rather than encouraged. If a contract is that complex, its components should be extracted out either by making helper contract combinators or by defining new data types.

For the benefit to be apparent, the success contract doesn't have to be particularly verbose, just moreso than the failure contract. In fact, if the success contract is particularly verbose, factoring it out is likely to be an improvement just as you say.

Decisions about argument ordering are almost always slippery like that when abstractions get into the mix. After all, if the order isn't right the first time, then all it takes is one more abstraction to change it. They impact nothing but the liminal moments where abstractions are elusive, the times after things look like they could be better but before a specific improvement is ready to go.

> Plus, I really don't want the result type to do things in the exact opposite order of Rust's result type.

I think it's true that there's a lot of precedent for putting the success first. That could be important for newcomers.

I see Rust and OCaml both put the success first. Has OCaml's `result` type been around for long? (And while we're at it, where did the term "result" come from? It's just as vague as calling it "value," but at least "value" would make more sense in situations where the so-called "result" is passed in as an input.)

English has precedent like the phrases "yes or no," "win or lose," and "pass or fail." As a newcomer learning about Haskell's `Either`, I thought it would be a lot more readable if it followed the argument order implied by these English phrases.

Haskell has other things going on which mean its situation isn't analogous. Haskell types' argument ordering decisions are a bit more impactful; type constructors can only be partially applied in one order, and defining a new type constructor just to change the argument order means values have to be explicitly coerced back and forth all over the place. Since the `Monad (Either err)` instance needs to partially apply `Either` to the failure type, the argument order of `Either` is basically determined by circumstance.

So when I say putting the failure first is good for keeping operators and arguments in proximity of each other, I'm saying that regardless of whatever reasons the other languages have. :-p
