### ISSUE TITLE
Should `deduplicating` transducer have more features?

### ISSUE THREAD

**Issue by samdphillips** [jackfirth/rebellion#310]
I'm wondering if it should have this signature,

`(deduplicating [#:equal (-> any/c any/c boolean?)] [#:in-order? boolean?])`

Using `#:equal` would allow for other types of equality like case-insensitive deduplication.

Using `#:sorted?` would be an optimization that allows for emitting elements without having to consume all of the input.

**Comment by jackfirth** [comment]
Case-insensitive string deduplication sounds really useful, so I think you're onto something. A key function argument would make it easy to deduplicate dictionary entries too. Maybe there could be an `equivalence?` object similar to comparators?

Not totally sure what other features it should have, but I think at the least `deduplicating` should be changed from a constant to a zero-argument function. That way we can make sure adding new features is backwards compatible.

**Comment by jackfirth** [comment]
Hmm, for the sorted sequence case, what do you think of adding a second transducer that promises to only remove _consecutive_ duplicates? So you'd get something like this:

```
> (transduce (list 2 2 2 2 7 7 7 3 3 1 1 7 7)
             (deduplicating-consecutive)
             #:into into-list
(list 2 7 3 1 7)
```

Enabling this behavior with a keyword on `deduplicating` seems odd to me, because if the input sequence isn't sorted / contains nonconsecutive duplicates what should the transducer do? Throw an error? Silently break its expected behavior?

**Comment by samdphillips** [comment]
Yeah both of these sound like good ideas.

**Comment by jackfirth** [comment]
Added equivalence relations yesterday, so this can be implemented now. Proposed API:

```racket
(deduplicating [equivalence equivalence-relation? natural-equality]
               [#:key key-function (-> any/c any/c) values])
  -> transducer?

(deduplicating-consecutive [equivalence equivalence-relation? natural-equality]
                           [#:key key-function (-> any/c any/c) values])
  -> transducer?
```

Examples:

```racket
> (transduce (list "foo" "Foo" "fOo" "bar" "BAR" "FOO")
             (deduplicating (make-equivalence-relation string-ci=?))
             #:into into-list)
(list "foo" "bar")
> (transduce (list "foo" "Foo" "fOo" "bar" "BAR" "FOO")
             (deduplicating-consecutive (make-equivalence-relation string-ci=?))
             #:into into-list)
(list "foo" "bar" "FOO")
> (transduce (list "the" "quick" "brown" "fox")
             (deduplicating #:key string-length)
             #:into into-list)
(list "the" "quick")
```

The equivalence relation is a positional argument instead of a keyword argument for a few reasons:

1. Consistency with `sorting`, `into-min`, and `into-max`, each of which also takes an optional positional binary relation.
2. It feels like a more "important" argument than the key function. After all, the key function is basically just a shorthand for calling `equivalence-relation-map`.
3. The keyword name would just repeat the type. For the key function, the `#:key` keyword name helps communicate that this isn't just any function, it's a function used to extract the comparison key for each element. But for the equivalence relation argument, there's pretty much only one sensible way that it can be used, and if it did have a keyword it would be something like `#:equivalence` that just adds needless verbosity.

**Comment by jackfirth** [comment]
Hmmm. When I went to implement this, I realized: I have no idea how to efficiently implement `deduplicating` with an arbitrary equivalence relation. The current implementation shoves values into a set, which only works for `equal?` based comparisons. A custom equivalence relation can't even use a custom set type efficiently because there's no guarantee that equivalent values have equal hash codes. I think I'll ditch the equivalence relation arguments and only provide the key function arguments. For case-insensitive string comparisons, a key function that case-normalizes the string would work just as well anyway.
